### ISSUE TITLE
Invalid US-ASCII character when compiling

### ISSUE THREAD

**Issue by mitchellbusby** [unmaya/Girder#3]
When compiling the Sass source code in Koala, the following error appears: 
'Invalid US-ASCII character "\xC3"'
I've isolated the issue to be on line 14 of the _girder_function.scss file, where a '+' character has an invalid US-ASCII character. Replacing the '+' with a keyboard '+' on Mac OS X resolves the issue.

**Comment by mitchellbusby** [comment]
Hi @unmaya, do you plan on fixing this in the source code?

**Comment by mitchellbusby** [comment]
Hey @unmaya, could you please accept this pull request?

**Comment by unmaya** [comment]
Hi @mitchellbusby Sorry I thought that I had already responded to this. I was not able to reproduce this issue (osx or win). The line you reference accepts arbitrary input as a parameter which itself could be an invalid ASCII character.
